name: Gauge Pipeline

on: push

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    # - name: Install Gauge
    #     run: |
    #       wget https://downloads.gauge.org/stable 
    #       sh stable.sh
    #       export PATH=$PATH:$HOME/.gauge/bin

    - name: Install Gauge
      run: |
        Invoke-WebRequest -Uri https://downloads.gauge.org/stable -OutFile stable.zip
        Expand-Archive -Path stable.zip -DestinationPath $env:USERPROFILE\gauge
        $env:PATH += ";$env:USERPROFILE\gauge"
      shell: powershell

    # Debug step to check if Gauge path is set correctly
    - name: Check environment variables
      run: echo $env:PATH
      shell: powershell

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        gauge install python
        pip install flake8 pytest
        pip install -r requirements.txt

    - name: Run tests
      run: gauge run .//business_functions/specs_api/
      
    - name: Upload test results
      if: always()  # Ensure this step runs even if previous steps fail
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: reports/
