name: Gauge Pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Gauge
      run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 023EDB0B
          echo deb https://downloads.gauge.org/stable apt/ | sudo tee -a /etc/apt/sources.list.d/gauge.list
          sudo apt-get update
          sudo apt-get install gauge
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        gauge install python
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: gauge run business_functions/specs/

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: reports/
