name: Gauge Pipeline

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Gauge
        run: |
          wget -O gauge_installer.sh https://downloads.gauge.org/stable 
          sh gauge_installer.sh
          export PATH="${HOME}/.gauge/bin:${PATH}"
          
      - name: Print Gauge Version
        run: |
          gauge --version
          python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          gauge install python
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          playwright install
          

      - name: Run tests
        run: gauge run business_functions/specs/

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: reports/
