name: Gauge Pipeline

on:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; 
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; 
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        shell: powershell


      - name: Install Gauge and Python
        run: |
          choco install gauge python -y --no-progress
        shell: powershell

      - name: Add Gauge and Python to PATH
        run: |
          $gaugePath = "C:\Program Files\Gauge\bin"
          $pythonPath = "C:\Python39\Scripts"
          $env:PATH += ";$gaugePath;$pythonPath"
          echo "PATH=$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
        shell: powershell

      - name: Verify Gauge and Python Installation
        run: |
          gauge --version
          python --version
        shell: powershell

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
          playwright install
        shell: powershell

      - name: Check Runner IP Address
        run: |
          curl ifconfig.me
        shell: bash

      - name: Set Gauge Environment Variables
        run: |
          echo "GAUGE_HOST=localhost" >> $env:GITHUB_ENV
          echo "GAUGE_PORT=6000" >> $env:GITHUB_ENV
        shell: powershell

      - name: Wait before running tests
        run: Start-Sleep -Seconds 10
        shell: powershell

      - name: Run tests
        run: gauge run ./business_functions/specs_api/
        shell: powershell

      - name: Upload test results
        if: always() # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: reports/

      - name: Debug Network Ports
        run: netstat -a -n | findstr 1100
        shell: powershell
