name: Gauge Pipeline

on:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Gauge
        run: |
          Invoke-WebRequest -Uri https://downloads.gauge.org/stable -OutFile stable.exe
          Start-Process -FilePath ./stable.exe -ArgumentList "/silent" -Wait
          $env:PATH += ";$env:ProgramFiles\Gauge\bin"
        shell: powershell
          
      - name: Print Gauge Version
        run: |
          gauge --version
          python --version
        shell: powershell

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          gauge install python
          pip install flake8 pytest
          pip install -r requirements.txt
          playwright install
        shell: powershell
          
      - name: Run tests
        run: gauge run ./business_functions/specs_api/
        shell: powershell

      - name: Upload test results
        if: always() # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: reports/
