name: Gauge Pipeline

on:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Gauge
        run: |
         Invoke-WebRequest -Uri https://downloads.gauge.org/stable -OutFile stable.zip
         Expand-Archive -Path stable.zip -DestinationPath $env:USERPROFILE\gauge
         $env:PATH += ";$env:USERPROFILE\gauge"
        shell: powershell
          
      - name: Print Gauge Version
        run: |
          gauge --version
          python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          gauge install python
          pip install flake8 pytest
          pip install -r requirements.txt
          playwright install
          
      - name: Run tests
        run: gauge run ./business_functions/specs_api/

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: reports/
