name: Gauge Pipeline

on:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; 
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; 
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        shell: powershell

      - name: Install Gauge
        run: choco install gauge -y --no-progress
        shell: powershell
        

      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.12.5          

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
          playwright install
        shell: powershell

      - name: Check Runner IP Address
        run: curl ifconfig.me
        shell: bash

      - name: Run UI tests
        run: C:\"Program Files"\gauge\bin\gauge.exe run ./business_functions/specs/ --tags positivetest,uitest
        shell: powershell
      
      - name: Upload UI logs
        if: always() # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: test-logs-ui
          path: logs/

      - name: Upload UI test results
        if: always() # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results-ui
          path: reports/

      - name: Run API tests
        run: C:\"Program Files"\gauge\bin\gauge.exe run ./business_functions/specs/specs_api/ --tags apitest
        shell: powershell
        
      - name: Upload api logs
        if: always() # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: logs/

      - name: Upload api test results
        if: always() # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: reports/
