name: Gauge Pipeline

on:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; 
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; 
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        shell: powershell

      - name: Install Gauge, Python, and Other Tools
        run: |
          choco install gauge python flake8 pytest -y --no-progress
        shell: powershell

      - name: Add Python to PATH
        run: |
          $env:PATH += ";C:\Python39\Scripts;C:\Python39"
          echo "PATH=$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
        shell: powershell

      - name: Print Versions
        run: |
          gauge --version
          python --version
          flake8 --version
          pytest --version
        shell: powershell

      - name: Install Gauge Python Plugin and Other Dependencies
        run: |
          gauge install python
          pip install -r requirements.txt
          playwright install
        shell: powershell
          
      - name: Wait before running tests
        run: Start-Sleep -Seconds 10
        shell: powershell

      - name: Run tests
        run: gauge run ./business_functions/specs_api/
        shell: powershell

      - name: Upload test results
        if: always() # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: reports/
